# Generated by Django 2.1.1 on 2018-09-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('likes', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('photographer', models.CharField(max_length=100)),
                ('description', models.CharField(default='A sample image.', max_length=100)),
                ('img_url', models.CharField(max_length=300)),
            ],
        ),
    ]
